name: 🐛 Bug Report & Feedback
description: Something isn't working, or you'd like to suggest an improvement?
title: "[BUG] Short description or suggestion"
labels: [bug, feedback]
body:
  - type: markdown
    attributes:
      value: >-
        <h1 align="center">🚨 PLEASE READ BEFORE SUBMITTING 🚨</h1>

        ## Common Issues – Do NOT Report These

        - **Media Cannot Be Played / Login Required / Unknown Error**  
          Likely caused by YouTube blocking the content. Not a bug in RiMusic.

        - **Download Unsuccessful**  
          If *some* songs download and others don’t, you’re being rate-limited by YouTube. Use manual downloads with time gaps.

        - **Downloaded Songs Don’t Play**  
          Try:
          1. Re-downloading the song
          2. Clearing cache
          3. Playing the file directly from your device

        ✅ Only proceed if your issue is **not listed above**.

  - type: markdown
    attributes:
      value: >-
        ## 📋 Bug Report Form

        > Please complete this form accurately. More detail = faster fix!

  - type: input
    id: bug_occurs_in_version
    attributes:
      label: * App Version
      description: Which version of RiMusic are you using?
      placeholder: e.g., 0.6.56 - customVersion
    validations:
      required: true

  - type: dropdown
    id: android_version
    attributes:
      label: * Android Version
      description: Your device’s Android version
      options:
        - '7.0'
        - '7.1 - 7.1.2'
        - '8.0'
        - '8.1'
        - '9'
        - '10'
        - '11'
        - '12'
        - '13'
        - '14'
        - '15'
    validations:
      required: true

  - type: input
    id: device_model
    attributes:
      label: Device Model
      description: Device you’re using (e.g., Samsung A52, Pixel 5)
      placeholder: Redmi Note 10, OnePlus Nord 2
    validations:
      required: false

  - type: checkboxes
    id: verify_steps
    attributes:
      label: * Pre-Submission Checklist
      description: Please confirm:
      options:
        - label: I uninstalled the previous build before installing a new one
          required: true
        - label: I searched existing issues for similar problems
          required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: * Steps to Reproduce the Bug
      description: Step-by-step description of how to trigger the bug.
      value: |-
        1. Open RiMusic
        2. Click on feature X
        3. Observe error or crash
    validations:
      required: true

  - type: input
    id: expected_behavior
    attributes:
      label: * Expected Behavior
      description: What did you expect to happen?
      placeholder: Music should play without lag after pressing play.
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: What Actually Happened?
      description: What did the app do instead?
      placeholder: Music stuttered, and the app froze for 10 seconds.

  - type: textarea
    id: evidence
    attributes:
      label: (Optional) Video or Screenshot Evidence
      description: Upload a screen recording or screenshot. Size limit: 10MB.
      placeholder: Drag files here or paste links from Google Drive, Imgur, etc.

  - type: textarea
    id: app_logs
    attributes:
      label: (Optional) App Logs
      description: If accessible, paste logs here.

  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Any other details we should know?
      placeholder: The bug happens only when the phone is charging.

  - type: markdown
    attributes:
      value: >-

  - type: textarea
    id: \sarathiq
    attributes:
      label:  UI Suggestion
      description: Let us know what features you want in the future (optional)
      placeholder: Add dark mode toggle, option to download album art, more sort/filter features

  - type: checkboxes
    id: ui_rating
    attributes:
      label: sarathiq
      options:
        - label: Easy to use
        - label: Needs improvement
        - label: Too cluttered
        - label: Modern and smooth
        - label: Missing important settings

  - type: markdown
    attributes:
      value: >-
        _This form was built using [Issue Forms Creator](https://issue-forms-creator.netlify.app). Thanks for helping improve RiMusic!_
