name: Feature Request
description: Suggest an idea for this project
labels: "[feature]"
body:

  - type: textarea
    id: featurebyproblem
    attributes:
      label: Is your feature request related to a problem?
      description:  Please describe. 
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]       
    validations:
      required: true

   - type: textarea
    id: describesolution
    attributes:
      label: Describe the solution you'd like
      description:  Please describe. 
      placeholder: A clear and concise description of what you want to happen.       
    validations:
      required: true

    - type: textarea
    id: describealternative
    attributes:
      label: Describe alternatives you've considered.
      description:  Please describe. 
      placeholder: A clear and concise description of any alternative solutions or features you've considered.      
    validations:
      required: false

    - type: textarea
    id: additionalinfo
    attributes:
      label: Additional info 
      description:  Please describe. 
      placeholder: Any other additional info? Insert here
    validations:
      required: false
