name: Update contributors list in app

on:
  schedule:
    - cron: '0 16 * * 5' # Every Friday at 16:00
  # Allow manual trigger
  workflow_dispatch:

jobs:
  update-contributors-list:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install BeautifulSoup4 dependency
        run: pip install beautifulsoup4 requests

      - uses: actions/checkout@v4.2.0

      - name: Run get_developes.py script
        run: python get_developers.py

      - name: Copy generated contributors.json to its correct place
        run: "mv contributors.json composeApp/src/androidMain/res/raw/contributors.json"
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%m-%d-%Y')" >> $GITHUB_OUTPUT

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "In app contributors list updated ${{ steps.date.outputs.date }}"
